name: Unit Tests

on: push

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Build PCG (tests depend on it)
        run: make pcg

      - name: Run Tests
        run: make test
